//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs.Abstractions.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jobs.Abstractions.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The &apos;Deny&apos; strategy prevents jobs from being added to the &apos;JobManager&apos;. If different behavior is required, consider a different strategy..
        /// </summary>
        internal static string AddDenyStrategyTryAdd {
            get {
                return ResourceManager.GetString("AddDenyStrategyTryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding &apos;Job&apos; to a disposable &apos;JobManager&apos; makes no sense. To create a reusable &apos;JobManager&apos;, set the &apos;JobManagerOptions.Disposable&apos; property to &apos;false&apos;..
        /// </summary>
        internal static string AddJobInDisposableManager {
            get {
                return ResourceManager.GetString("AddJobInDisposableManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A completed job was called. If you use JobManager for jobs, consider setting the JobManagerOptions.Clean property to true or setting the Job.Status property to StatusJob.None at the end of the Job.RunAsync method..
        /// </summary>
        internal static string CallCompletedJob {
            get {
                return ResourceManager.GetString("CallCompletedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jobs in &apos;JobManager&apos; are already running..
        /// </summary>
        internal static string CallJobManagerInProccess {
            get {
                return ResourceManager.GetString("CallJobManagerInProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The add strategy must be from the &apos;AddStrategy&apos; enumeration..
        /// </summary>
        internal static string UnknownAddStrategy {
            get {
                return ResourceManager.GetString("UnknownAddStrategy", resourceCulture);
            }
        }
    }
}
